### ISSUE TITLE
B Corp hex map by sector.

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#36]
As an additional B Corp hex map, could we have a slider that shows the distribution by sector?

Hopefully the sector is available form the B Corp company list we scraped.

**Comment by slowe** [comment]
The B Corp data contains "Industry" but these include all the following: 

* Accommodation
* Accounting & auditing
* Admin, photocopying & mail services
* Advertising & market research
* Agicultural support/post-harvest
* Agricultural Processing
* Animal Production
* Apparel
* Architecture design & planning
* Arts & entertainment
* Athletic & fitness centers
* Beverages
* Book publishing
* Books or other media
* Call centers
* Chemicals & chemical products
* Civil engineering
* Cleaning products
* Computer & electronic products
* Computer programming services
* Computers & electronics
* Construction
* Contracting & building
* Data processing & hosting
* Deposit bank - Developed Markets
* Design & building
* Diagnostic services
* Education & training services
* Educational support
* Electrical equipment
* Employment placement & HR
* Engineering
* Environmental consulting
* Equity investing - Developed Markets
* Equity investing - Emerging Markets
* Event catering & related
* Fabricated metal products
* Facilities & cleaning services
* Film, TV & music production
* Financial markets exchanges
* Financial transaction processing
* Food products
* Funeral & related services
* Furniture
* Games & toys
* General retail via Internet
* General second-hand goods
* General stores
* Growing non-perennial crops
* Growing perennial crops
* Hairdressing & other beauty services
* Health insurance
* Home health care
* Intellectual property leasing ex-copyrighted
* Investment advising
* Jewelry & related articles
* Landscape services
* Laundry & dry-cleaning
* Leather & related products
* Legal activities
* Life insurance
* Machinery & equipment
* Management  consultant - for-profits
* Management consultant - nonprofits
* Materials recovery & recycling
* Medical & dental practice
* Medical & dental supplies
* Membership organizations
* Mixed Farming
* Mobile applications
* Non-life insurance
* Other business support
* Other credit - Developed Markets
* Other education
* Other financial services
* Other human health
* Other info service activities
* Other install & construction
* Other insurance services
* Other manufacturing
* Other personal services
* Other power generation
* Other professional, scientific & tech
* Other publishing activities
* Other recreation
* Other renewable energy installation
* Other retail sale
* Other sports
* Other transport equipment
* Other/general wholesale trade
* Paper & paper products
* Pension/retirement plans
* Personal care products
* Pharmaceutical products
* Photography
* Postal & courier activities
* Pre- & primary education
* Printing & recorded media
* Programming & broadcasting
* Publishing - newspapers & magazines
* Real estate - leased property
* Real estate development
* Real estate- fee/contract
* Rent/lease: other goods
* Residential elderly & disabled care
* Restaurants & food service
* Rubber & plastics products
* Scientific R&D
* Social networks & info sharing
* Software publishing and SaaS platforms
* Solar panel installation
* Solar power generation
* Spec design (non-building)
* Sports goods
* Technology-based support services
* Telecommunications
* Textiles
* Transportation support
* Travel agency & related
* Veterinary activities
* Waste collection
* Web portals
* Wood & wood products

I think this is too many different things to include them all in a hex map firstly because it means a poor interface but there will also be very few things per industry+area.

**Comment by slowe** [comment]
Forget that. I've realised they also give sector. That seems to boil down to:

* Manufacturing
* Agriculture/Growers
* Service with Significant Environmental Footprint
* Service
* Service with Minor Environmental Footprint
* Wholesale/Retail

**Comment by luke-strange** [comment]
Looks good. I'm guessing those are B Corps own sectors?

**Comment by slowe** [comment]
I will have a look at adding them to the big CSV file breakdown by LA.

**Comment by slowe** [comment]
On page 10 of https://pardot.bcorporation.net/l/39792/2023-02-07/9rblgc/39792/1675785775pOkvYjFy/Guide_to_the_B_Corp_Certification_Process.pdf# I found the B Corp defined sectors listed as:

* Service with Minor Environmental Footprint
* Service with Significant Environmental Footprint
* Wholesale/Retail
* Manufacturing
* Agriculture

Which doesn't include `Service`, and `Agriculture` has been listed as `Agriculture/Growers` in the data.
