### ISSUE TITLE
Add links to dashboard panels

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/true-north#39]
Brabners would like the ability to link to new pages by linking from the dashboard panels.

I'm unsure what the best approach would be.

It could be to have a "link" column in the csv data file, and incorporate this into OI lume charts.

Or is there a way to wrap each individual panel with a <a> tag in the index.vto file?

**Comment by slowe** [comment]
In answer to the question, no. Because the index.vto file won't give you access to individual panels in a `dashboard` component. There's a couple of ways that I could interpret "ability to link to new pages by linking from the dashboard panels":

1. A link in a footnote. In this case you can (with existing functionality) create a new column for the footnote that builds a hyperlink from a suitable column in the CSV.
2. Making the entire panel into a link. This isn't currently a feature. We should think through the implications and where this could go wrong/break.

**Comment by luke-strange** [comment]
We could go with a link in the footnote for now, since that sounds easier to implement given the time we have available. What would be the best approach to do this?

**Comment by slowe** [comment]
Create [a virtual column](https://open-innovations.github.io/oi-lume-viz/documentation/virtual-columns/) that builds a link. Refer to this column as the `note`.

**Comment by luke-strange** [comment]
This is done for now. Will just need to add relevant links as they become available on the site.
